version: "3.8"

services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: quiz_user
      POSTGRES_PASSWORD: LkvKmBoQvYIuz1ogpJrc
      POSTGRES_DB: quizdinamico
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
